Error detected while processing function ReloadFolds:
line   23:
E121: Undefined variable: b:anyfold_ind_actual

Error detected while processing function Cycle_csdb:
line   15:
E609: Cscope error: cscope: cannot open file /media/volgrp/mirror/av/cscope.out.in
Press ENTER or type command to continue

cscope: cannot read trailer offset from file cscope.out
fugitive: fatal: not under version control, source=kvmrc/v2qcow2.sh, destination=kvmrc/vmdk2qcow2.sh

 E325: ATTENTION
"imvu/website/gdio.diff" 45L, 2473C
[ncm2_tern@yarp] Traceback (most recent call last):
[ncm2_tern@yarp]   File "/Users/yhuang/.vim/bundle/nvim-yarp/pythonx/yarp.py", line 65, in <module>
[ncm2_tern@yarp]     module_obj = importlib.import_module(module)
[ncm2_tern@yarp]   File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
[ncm2_tern@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[ncm2_tern@yarp]   File "/Users/yhuang/.vim/bundle/ncm2-tern/pythonx/ncm2_tern.py", line 188, in <module>
[ncm2_tern@yarp]     source = Source(vim)
[ncm2_tern@yarp]   File "/Users/yhuang/.vim/bundle/ncm2-tern/pythonx/ncm2_tern.py", line 103, in __init__
[ncm2_tern@yarp]     'split(globpath(&rtp,"node_modules/tern/bin/tern",1),"\\n")[0]')
[ncm2_tern@yarp]   File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 295, in eval
[ncm2_tern@yarp]     return self.request('nvim_eval', string, **kwargs)
[ncm2_tern@yarp]   File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
[ncm2_tern@yarp]     res = self._session.request(name, *args, **kwargs)
[ncm2_tern@yarp]   File "/usr/local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
[ncm2_tern@yarp]     raise self.error_wrapper(err)
[ncm2_tern@yarp] pynvim.api.nvim.NvimError: b'Vim:E684: list index out of range: 0'
[ncm2_tern@yarp] Job is dead. cmd=['/usr/local/opt/python/bin/python3.7', '-u', '/Users/yhuang/.vim/bundle/nvim-yarp/pythonx/yarp.py', '/var/folders/zn/6zwn3dz13v3fdjtrsh9g_dv9ymvzkm
/T/nvimUidvlP/0', 12, 'ncm2_tern']


GetEscapedKeyword
Not\_s\+authorized\_s\+for\_s\+request
Not\ \+authorized\ \+for\ \+request
Not \+authorized \+for \+request

Error detected while processing function <SNR>24_auto_deploy_augroup[6]..asyncrun#run[102]..<SNR>44_run[63]..<SNR>AsyncRun_Job_Start:
line  101:
E903: Process failed to start: too many open files: "/bin/bash"

cscope: No such file or directory
cscope: cannot rename file ncscope.out.bak to file cscope.out.bak

Error detected while processing BufReadCmd Autocommands for "index{,.lock}":
fugitive: error: key does not contain a section: GIT_INDEX_FILE^@fatal: unable to parse command-line config

Error detected while processing function 87:
line   41:
E121: Undefined variable: l:changed_win_bufs
E15: Invalid expression: l:changed_win_bufs

Cought anything: Vim(cd):E472: Command failed

[ncm2_go@yarp] TypeError: expected str, bytes or os.PathLike object, not NoneType
[ncm2_pyclang_proc@yarp] try_notify cache_add failed, job is dead

The legacy SnipMate parser is deprecated. Please see :h SnipMate-deprecate.
[ncm2_tmux@yarp] subprocess.TimeoutExpired: Command '['tmux', 'display-message', '-p', '#{session_id}']' timed out after 5 seconds
vimrc/.vim/bundle/ncm2-tmux/pythonx/ncm2_tmux.py:18:        proc = Popen(args=['tmux', 'display-message', '-p', '#{session_id}'],
[ncm2_tmux_complete@yarp] subprocess.CalledProcessError: Command '['sh', '-c', "sh ...xcomplete' -p '^.' -s 'words' -l '-a' -c '' -g ''"]' died with <Signals.SIGKILL: 9>.
[ncm2_tern@yarp] Job is dead. cmd=['/usr/local/opt/python@3.9/bin/python3.9', '-u',...', '/var/folders/7z/251_ly552l9glm39cnj9zxrh0000gn/T/nvimGXqrxd/0', 13, 'ncm2_tern']
[ncm2_tmux_complete@yarp] subprocess.CalledProcessError: Command '['sh', '-c', "sh ...xcomplete' -p '^.' -s 'words' -l '-a' -c '' -g ''"]' died with <Signals.SIGKILL: 9>.
[ncm2_tmux_complete@yarp] subprocess.CalledProcessError: Command '['sh', '-c', "sh '/Users/huangyingw/loadrc/vimrc/.vim/bundle/tmux-complete.vim/sh/tmuxcomplete' -p '^.' -s
[ncm2_tern@yarp] Job is dead. cmd=['/usr/local/opt/python@3.9/bin/python...ders/zn/6zwn3dz13v3fdjtrsh9g_dv9ymvzkm/T/nvimUC0moc/0', 13, 'ncm2_tern']
[ncm2_jedi@yarp] Job is dead. cmd=['/root/anaconda3/bin/python3', '-u', '/root/.vim/bundle/nvim-yarp/pythonx/yarp.py', '/tmp/nvimEcygXB/0', 6, 'ncm2_jedi']


Error detected while processing function provider#clipboard#Call[6]..6:
line    8:
E691: Can only compare List with List
Error detected while processing function provider#clipboard#Call[6]..6:
line    8:
E15: Invalid expression: match(&clipboard, '\v(unnamed|unnamedplus)') >= 0 && get(s:selections[a:reg].data, 0, []) ==# clipboard_data
clipboard: provider returned invalid data
Error detected while processing function CSCSearch[12]..GetEscapedResult:
line   17:
E33: No previous substitute regular expression
Error detected while processing function VFilter[5]..Filter2Findresult[3]..GetEscapedResult:
line   17:
E33: No previous substitute regular expression

Error detected while processing function ResCur:
line    2:
E20: Mark not set

Error detected while processing function VFilter:
line    7:
E207: Can't delete backup file

Error detected while processing function ExFilter:
line    7:
E207: Can't delete backup file

E576: Error while reading ShaDa file: last entry specified that it occupies 142 bytes, but file ended earlier
E136: Did not rename /Users/huangyingw/.viminfo.tmp.h because /Users/huangyingw/.viminfo does not look like a ShaDa file
E136: Do not forget to remove /Users/huangyingw/.viminfo.tmp.h or rename it manually to /Users/huangyingw/.viminfo.

zrecompile:99: fork failed: resource temporarily unavailable
/Users/huangyingw/.oh-my-zsh/plugins/helm/helm.plugin.zsh:12: fork failed: resource temporarily unavailable
nvm_supports_source_options:2: fork failed: resource temporarily unavailable
_zsh_nvm_rename_function:1: fork failed: resource temporarily unavailable
/Users/huangyingw/loadrc/.envrc:3: fork failed: resource temporarily unavailable
/Users/huangyingw/loadrc/.mbp2.rc:4: fork failed: resource temporarily unavailable
2022-10-29 10:46:08.292 systemsetup[35401:3283514] ### Error:-99 File:/AppleInternal/Library/BuildRoots/810eba08-405a-11ed-86e9-6af958a02716/Library/Cac
hes/com.apple.xbs/Sources/Admin/InternetServices.m Line:379
setcomputersleep: Never

Error detected while processing function tig_explorer#open_current_file[2]..tig_explorer#open[1]..<SNR>189_exec_tig_command[11]..function tig_explorer#open_current_file[2
]..tig_explorer#open[1]..<SNR>189 exec_tig_command:
vimrc/.vim/bundle/tig-explorer.vim/autoload/tig_explorer.vim:235 function! s:exec_tig_command(tig_args) abort
line    9:
tig-explorer.vim: Not a git repository: /Users/huangyingw/loadrc/tests/space in dir name
tig: No revisions match the given arguments.

Error detected while processing CursorMoved Autocommands for "<buffer=5>"..script /root/loadrc/vimrc/.vim/bundle/python-mode/autoload/pymode/lint.vim[1]..function provider#python3#Ca
ll:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/loadrc/vimrc/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
    from pylama.lint.extensions import LINTERS
  File "/root/loadrc/vimrc/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 38, in <module>
    from pkg_resources import iter_entry_points
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 82, in <module>
    from pkg_resources.extern import platformdirs
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 52, in create_module
    return self.load_module(spec.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 44, in load_module
    raise ImportError(
ImportError: The 'platformdirs' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
